//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.SqlServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Libro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Libro()
        {
            this.Intercambio = new HashSet<Intercambio>();
            this.Intercambio1 = new HashSet<Intercambio>();
        }
    
        public int IdLibro { get; set; }
        public string Nombre { get; set; }
        public string Resenia { get; set; }
        public string Imagen { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<System.DateTime> FechaAdquisicion { get; set; }
        public string Estado { get; set; }
        public Nullable<int> IdGenero { get; set; }
        public Nullable<int> IdAutor { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public string Activo { get; set; }
    
        public virtual Autor Autor { get; set; }
        public virtual Genero Genero { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Intercambio> Intercambio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Intercambio> Intercambio1 { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
